###
GET http://localhost:8080/user/add
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/user/add?ds=a
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/user/add?ds2=b
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/user/add?ds=a&ds2=b
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/user/json
Content-Type: application/json

{
  "name": "zs",
  "pwd": "1234"
}

### bug 第一次请求不会成功，第二次请求才会应用第一次请求的参数
